### PR TITLE
DEV: Fix noisy specs

### PR DESCRIPTION
**Pull request by CvX**

### CODE REVIEW

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
hmmm but what is the root cause here of the stdout stuff?

**Comment by CvX** [comment]
@SamSaffron The automation in specs outputs data by design (see: https://github.com/discourse/discourse-automation/blob/main/spec/discourse_automation_helper.rb#L6) and in most cases we already capture the output to assert that it contains what we need. But in those three places we don't care about the emitted stuff, so it was just printed out.

**Comment by SamSaffron** [comment]
I would like this expanded, can we open a dev topic. 

What value are we getting in production from polluting stdout in our unicorn processes? Why is this not shipped to logs in verbose mode if it is important?

**Comment by CvX** [comment]
It's a test-only thing. It's a mock automation, and all it does is to print out its inputs. It's used to assert the correctness of params.

**Comment by SamSaffron** [comment]
I see, missed the point it was test-only ... carry on... no need for a dev topic.

**Pull request merged**
